/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_ndksample_MainActivity */

#ifndef _Included_com_android_ndksample_MainActivity
#define _Included_com_android_ndksample_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_ndksample_MainActivity
 * Method:    nativeFibonacci
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_android_ndksample_MainActivity_nativeFibonacci(
		JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
