/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_ndksample_NativeFibonacci */

#ifndef _Included_com_android_ndksample_NativeFibonacci
#define _Included_com_android_ndksample_NativeFibonacci
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_ndksample_NativeFibonacci
 * Method:    recursiveNative
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_android_ndksample_NativeFibonacci_recursiveNative
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
